; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
; own defs
;platform = https://github.com/maxgerhardt/platform-raspberrypi.git#9f8c10e
; board can use both Arduino cores -- we select Arduino-Pico here
board_build.core = earlephilhower

;upload_protocol = mbed
;debug_tool = jlink
;debug_extra_cmds = 
;  set output-radix 16

lib_deps = 
	https://github.com/thelsing/knx#Flash_batchwrite
	https://github.com/OpenKNX/OGM-Common#modular

lib_ldf_mode = deep+
build_flags = 
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_RTTI
	-DLWIP_DONT_PROVIDE_BYTEORDER_FUNCTIONS
	-DMASK_VERSION=0x07B0
	-DKNX_FLASH_SIZE=4096
    -DKNX_NO_SPI
	-Wno-unknown-pragmas
    -DSERIAL_DEBUG=Serial
    -DSMALL_GROUPOBJECT